# Model configs
model_name: 'TripletNetBaseline'
model_params:
  base: 'resnet50'
  pretrained: True
  feat_vect_size: 512 # Using nn.Linear(model_out, feat_vect_size)

# Training configs
batch_size: 512
n_epochs: 4000
decay_epochs: [2000, 3000]
init_lr: 1e-3
lr_decay: 0.1  # decaying rate for learning rate

#Optimizer configs
optimizer_name: SGD
optimizer_params:
  momentum: 0.9
  nesterov: True
weight_decay: 1e-4

n_epochs_to_log: 1000
n_epochs_to_eval: 50

#Image transform configs
transforms: #data augmentation 
  base: #apply for both train and test/evaluate
    resize: 
      size: 128
    to_tensor:
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# Loss function configs
loss_fn: 
  TripletLossBatchHard:
    margin: 1.0

#Sampler configs
sampler:
  BatchSampler:
    n_class: 64
    n_num  : 3
