# Model configs
model_name: 'TripletNetBaseline'
model_params:
  base: 'resnet50'
  pretrained: True
  feat_vect_size: 512 # Using nn.Linear(model_out, feat_vect_size)

# Training configs
batch_size: 32
n_epochs: 80
decay_epochs: [40,60]
init_lr: 1e-3
lr_decay: 0.1  # decaying rate for learning rate

#Optimizer configs
optimizer_name: Adam
optimizer_params:
  betas: [0.8, 0.999]

n_epochs_to_log: 5

#Image transform configs
transforms: #data augmentation 
  base: #apply for both train and test/evaluate
    resize: 
      size: 224
    # resize: 
    #   size: 256
    # center_crop: 
    #   size: 224
    to_tensor:
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# Loss function configs
loss_fn: 
  TripletLossBaseline:
    margin: 1.0